### ISSUE TITLE
Profile installers can set different helm values for each chart artifact

### ISSUE THREAD

**Issue by aclevername** [weaveworks/pctl#102]
## Introduction
Currently you can pass in a config map to your profile installation that gets passed down to all the HelmRelease artifacts as values. For example:

Configmap:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-values
data:
  values.yaml: |
    replicaCount: 3
    service:
      port: 8082

```

This can be passed in during install:

```
pctl install --config-secret nginx-values nginx-catalog/weaveworks-nginx
```

Resulting in:
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  creationTimestamp: null
  name: bitnami-bitnami-nginx-nginx-server
  namespace: default
spec:
  chart:
    spec:
      chart: bitnami-nginx/nginx/chart
      sourceRef:
        kind: GitRepository
        name: bitnami-profiles-examples-main
        namespace: default
  interval: 0s
  valuesFrom:
  - kind: ConfigMap
    name: nginx-values
    valuesKey: helm-values
status: {}
```

## Problem

If I have a profile that consists of two helm charts, A and B. Both helm charts expose a top level key `replica` in their values file for configuring the number of replicas. I want chart A to have 3 replicas and chart B to have 5.
With the current implementation you can only specify the `replica` key once, the same value gets passed down to both HelmRelease resources. We need a way to specify passing different helm values to different artifacts.

## Simple solution

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-values
data:
  name-of-artifact-1: |
    replicaCount: 3
  name-of-artifact-2.yaml: |
    replicaCount: 5
 ```
 
 ```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  creationTimestamp: null
  name: bitnami-bitnami-nginx-nginx-server
  namespace: default
spec:
  chart:
    spec:
      chart: bitnami-nginx/nginx/chart
      sourceRef:
        kind: GitRepository
        name: bitnami-profiles-examples-main
        namespace: default
  interval: 0s
  valuesFrom:
  - kind: ConfigMap
    name: nginx-values
    valuesKey: helm-B.yaml
status: {}
```

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  creationTimestamp: null
  name: bitnami-bitnami-nginx-nginx-server
  namespace: default
spec:
  chart:
    spec:
      chart: bitnami-nginx/nginx/chart
      sourceRef:
        kind: GitRepository
        name: bitnami-profiles-examples-main
        namespace: default
  interval: 0s
  valuesFrom:
  - kind: ConfigMap
    name: nginx-values
    valuesKey: helm-A.yaml
status: {}
```

Documentation has to be clear. The user has to learn the name of the artifacts they want to configure, and ensure that the keys under `data` exactly match the name of the artifact.
We should also verify that it is not possible to have artifacts with duplicate names. If it is possible, we should introduce a guard to ensure that all profile artifact names are unique (also docs).
