### ISSUE TITLE
pctl install from a profile definition that lives in a private repository

### ISSUE THREAD

**Issue by aclevername** [weaveworks/pctl#103]
**What feature/behavior/change do you want?**
I want to be able to `pctl install` from a profile that lives in a private git repository.

## Example
Lets say `github.com/private/dokuwiki` exists and contains the `dokuwiki` profile which consists only of a remote public helm chart:

```
apiVersion: profiles.fluxcd.io/v1alpha1
kind: Profile
metadata:
  name: dokuwiki
spec:
  description: Profile for deploying dokuwiki
  version: v0.1.0
  artifacts:
    - name: dokuwiki
      kind: HelmChart
      chart:
        url: https://charts.bitnami.com/bitnami
        name: dokuwiki
        version: "11.1.6"
```
We need to be able to fetch this `profile.yaml` from the private repository

** this issue does not handle private artifacts **
