### ISSUE TITLE
pctl install copies down remote artifacts

### ISSUE THREAD

**Issue by aclevername** [weaveworks/pctl#104]
**What feature/behavior/change do you want?**
Follow up from https://github.com/weaveworks/pctl/issues/103 we added support for installing a profile from a private repository. Now we have a problem that we reference artifacts in that remote repository, which is private. One solution is to ask the user to provide a secret that can be used to clone it, or we can clone those artifacts locally into the profile installation. We are going for the later.

## Example
Lets say `github.com/private/dokuwiki` exists and contains the `dokuwiki` profile which consists of a locally defined helm chart:

```
apiVersion: profiles.fluxcd.io/v1alpha1
kind: Profile
metadata:
  name: dokuwiki
spec:
  description: Profile for deploying local dokuwiki
  version: v0.0.1
  artifacts:
    - name: dokuwiki
      path: dokuwiki/chart
      kind: HelmChart
```

A user installs it via `pctl install my-catalog/dokuwiki`
```
├── dokuwiki
│   ├── GitRepository.yaml # pointing to github.com/private/dokuwiki to consume the local chart
│   └── HelmRelease.yaml
```
That GitRepository resource points to `github.com/private/dokuwiki` and is referenced in the `HelmRelease` resource

```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: bitnami-profiles-examples-main
  namespace: default
spec:
  interval: 0s
  ref:
    branch: main
  url: https://github.com/private/dokuwiki
```

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bitnami-bitnami-nginx-nginx-server
  namespace: default
spec:
  chart:
    spec:
      chart: dokuwiki/chart
      sourceRef:
        kind: GitRepository
        name: bitnami-profiles-examples-main
        namespace: default
```

We now instead want to copy down the `chart` definition, and have re-use the existing `GitRepository` resource (since the profile installation repo is already watched by some GitRepository resource)

## New installation
`pctl install dokuwiki --git-repository=<namespace>/<name>`
```
dokuwiki
├── chart
│   ├── Chart.yaml
│   └── templates
│       └── template-1.yaml
└── HelmRelease.yaml
```

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bitnami-bitnami-nginx-nginx-server
  namespace: default
spec:
  chart:
    spec:
      chart: dokuwiki/chart
      sourceRef:
        kind: GitRepository
        name: <name>
        namespace: <namespace>
```
