### ISSUE TITLE
pctl should auto-discover any secrets needed to clone gitrepository resources

### ISSUE THREAD

**Issue by aclevername** [weaveworks/pctl#106]
As part of https://github.com/weaveworks/pctl/issues/103 https://github.com/weaveworks/pctl/issues/104 we started adding support for private repositories, but the secret management is painful and has resulted us in relying on the user having the credentials locally for `pctl install` and asking the user what gitrepository resource points to there profile installation. A lot of this is a hack to get around asking the user to provide endless secrets. This issue describes an alternative approach to getting secrets, to hopefully remove this complexity.

## Proposal

pctl searches for a secret that can be used to clone a private repository, preventing the need for the user to know what secret to use.

### Example:

A cluster admin/catalog author creates a secret for accessing a repository that is private:
```
apiVersion: v1
kind: Secret
metadata:
  name: some-secret
  annotations:
    repo-url: https://github.com/aclevername/foo
  labels:
    profiles-git-secret: true
stringData:
  ssh-key: ... # whatever format flux GitRepository resources expect
```

The label `profile-git-secret` indicates this secret can be used for cloning a git repository. The annotation `repo-url` specifies what repo this secret can be used for. Ideally this would all be done via labels, but they are restrictive in what characters you can use, for example no slashes. Annotations do not have this restriction.

A user run `pctl install catalog/some-private-profile`. pctl detects this profile resolves to a private repository, so it goes about looking for a secret that can be used. pctl lists of all secrets with label `profiles-git-secret:true`, and parses them one-by-one looking for the secret with annotation `repo-url:  https://github.com/aclevername/foo`. Once it finds the secret it uses this secret in the `GitRepository` resource

This feature could and maybe should be part of `flux`, but lets implement it ourselves first. We can always switch out to a flux-native approach down the line
