### ISSUE TITLE
Sparse clone clones for each artifact. It should be more clever than that

### ISSUE THREAD

**Issue by Skarlso** [weaveworks/pctl#134]
After the refactor is done, have a think about how to better do the sparse cloning. If there are multiple artifacts for a single repo, it sparse clones on each artifact, instead of doing it once, then copying out the needed artifact details.

**Comment by Skarlso** [comment]
Local artifact: anything that lives in the profile definition's repository. Things like, deployment.yaml, chart.yaml...

For example, consider the following profiles.yaml file:

```yaml
apiVersion: weave.works/v1alpha1
kind: ProfileDefinition
metadata:
  name: weaveworks-nginx
spec:
  name: weaveworks-nginx
  description: Profile for deploying nginx
  maintainer: weaveworks
  prerequisites:
    - "kubernetes 1.19"
  artifacts:
    - name: nginx-deployment-1
      kustomize:
        path: nginx/deployment-1
    - name: nginx-deployment-2
      kustomize:
        path: nginx/deployment-2
```

These two artifacts are in the same repository. This should result in a single clone and thing to copy twice.

This code lives here: https://github.com/weaveworks/pctl/blob/7b8b82f7220d03f52ed0efa4b4cd4bb068fcde42/pkg/profile/artifact.go#L98

This function works through pathToCopy. But the problem is, that the Artifact is per artifacts instead of per ProfileDefinition.
Maybe have a higher level abstraction?
