### ISSUE TITLE
Label-based selector for artifacts to enable the concept of portable profiles

### ISSUE THREAD

**Issue by chanwit** [weaveworks/pctl#249]
A "portable profile" is a profile which is portable across Kubernetes platforms, for example EKS, GKE, K8s on prem, etc.

This document is to propose a way to enable the concept of portable profiles and a way to implement this concept using "label-based selector" for artifacts in the current v1alpha1 ProfileDefinition.

Here's an example of a working MLOps profile without artifact labels,

```
apiVersion: weave.works/v1alpha1
kind: ProfileDefinition
metadata:
  name: mlops
spec:
  description: A profile to deploy Kubeflow-based MLOps pipelines
  artifacts:
  - name: kfp-cluster-scoped
    kustomize:
      path: kfp-cluster-scoped
  - name: kfp
    kustomize:
      path: kfp
    dependsOn:
      - name: kfp-cluster-scoped
```

This document proposes that an artifact could be labelled and later the `pctl add` command could select a certain set of artifacts before add them to the GitOps repo.

Here's an example of a ProfileDefinition which contains artifacts their labels.

```
apiVersion: weave.works/v1alpha1
kind: ProfileDefinition
metadata:
  name: mlops
spec:
  description: A profile to deploy Kubeflow-based MLOps pipelines
  artifacts:
  - name: kfp-cluster-scoped
    kustomize:
      path: kfp-cluster-scoped
  - name: kfp-on-eks
    labels:
      platform: eks
    kustomize:
      path: kfp
    dependsOn:
      - name: kfp-cluster-scoped
  - name: kfp-on-azure
    labels:
      platform: azure
    kustomize:
      path: kfp
    dependsOn:
      - name: kfp-cluster-scoped
  - name: kfp-on-prem
    labels:
      platform: metal
    kustomize:
      path: kfp
    dependsOn:
      - name: kfp-cluster-scoped
```

A DAG of this ProfileDefinition is as followed, where the `pctl add` command could select `kfp-on-eks` artifact and its dependencies (`kfp-cluster-scoped` in this case). 
```
                                      ┌────────────────┐
                                      │                │
$ pctl add --select=platform=eks ...  │ kfp-on-eks     ├────────────────────────────────────┐
                                      │                │                                    │
                                      └────────────────┘                                    │
                                          platform: eks                                     │
                                                                                ┌───────────▼──────────┐
                                      ┌────────────────┐                        │                      │
                                      │                │                        │                      │
                                      │ kfp-on-azure   ├────────────────────────► kfp-cluster-scoped   │
                                      │                │                        │                      │
                                      └────────────────┘                        │                      │
                                          platform: azure                       └───────────▲──────────┘
                                                                                            │
                                      ┌────────────────┐                                    │
                                      │                │                                    │
                                      │ kfp-on-prem    ├────────────────────────────────────┘
                                      │                │
                                      └────────────────┘
                                          platform: metal
```

An example algorithm to implement this label-based selection when `platform=eks` is described as follows:
1. perform topology sorting over artifacts of the ProfileDefinition
2. find the starting artifact with the specified label. In this example, only `kfp-on-eks` is found.
3. traverse from the artifacts found in (2) to obtain their dependent artifacts.

Matching labels strategy
1. An artifact with a single label will be selected when the label is exactly matched.
2. An artifact with multiple labels will be selected when any of those labels is matched (logical OR).
3. An artifact without any label will be always selected.
