### ISSUE TITLE
Health Assessment for Artifacts

### ISSUE THREAD

**Issue by chanwit** [weaveworks/pctl#314]
As a Profile author,
I'd like to specify health assessments for each artifact in a Profile,
So that a complex deployment like Service Meshes + apps would be possible to deploy with Profiles.

**Problem**
A complex deployment like a Service Mesh requires everything to run properly (say every Deployment is ready) before deploying applications. To solve this problem, Flux supports the concept of Health Assessment via the HealthChecks field of Flux resources. 

A Profile author would be allowed to use the same feature to ensure that Profiles could be used to support complex deployments like Service Meshes and others.

**Comment by aclevername** [comment]
Thanks for opening the issue @chanwit ! Could you provide some examples of what you would want to happen? E.g. an example resource using flux's health assessment to ensure every deployment is ready? Thanks

**Comment by aclevername** [comment]
Thanks @chanwit , makes sense.

For `Helm` artifacts we already create a health check for the kustomization deploying the resource:
```
cat artifacts/nested-profile/nginx-server/kustomize-flux.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  creationTimestamp: null
  name: jake-nginx-server
  namespace: default
spec:
  healthChecks:
  - apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    name: jake-nginx-server
    namespace: default
  interval: 5m0s
  path: .wego/profiles/jake/artifacts/nested-profile/nginx-server/helm-chart
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: default
```

We could expand our profiledefintion spec to allow users to add health checks for `Kustomize` artifacts, e.g.:
```
apiVersion: weave.works/v1alpha1
kind: ProfileDefinition
metadata:
  name: weaveworks-nginx
spec:
  description: Profile for deploying nginx
  maintainer: weaveworks
  prerequisites:
    - "kubernetes 1.19"
  artifacts:
    - name: nginx-deployment
      kustomize:
        path: nginx/deployment
        healthChecks:
        - apiVersion: apps/v1
          kind: Deployment
          name: istio-operator
          # namespace: istio-operator exclude the namespace as we can set this dynamically depending on where the profile gets deployed

```

@chanwit would that solve your problem?
