### ISSUE TITLE
As a Profile Author I want to be able to provide a set of option for configuring raw-yaml artifacts

### ISSUE THREAD

**Issue by aclevername** [weaveworks/pctl#57]
As a Profile Author I want to be able to provide a set of option for configuring raw-yaml artifacts. I should be able to define what values are configurable in my profile definition. A consumer of the profile should be able to provide values for these configurations.

## Example
Given a profile:

``` bash
$ tree weaveworks-nginx/
├── profile.yaml
├── nginx
        ├── deployment.yaml
```

`profile.yaml` contains:
```yaml
apiVersion: profiles.fluxcd.io/v1alpha1
kind: Profile
metadata:
  name: weaveworks-nginx
spec:
  description: Profile for deploying nginx
  version: v0.1.0
  artifacts:
    - name: nginx
      path: nginx/
      kind: Kustomize
```
`nginx/deployment.yaml` contains:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
```

As a profile author I create a `profile_values.yaml` file containing:
```yaml
- key: container.image
  file: nginx/deployment.yaml
  patchDestination:
   - spec.template.spec.containers[0].image
- key: container.port
  file: nginx/deployment.yaml
  patchDestination:
   - spec.template.spec.containers[0].ports[0].containerPort
```

As a profile consumer I want to be able to provide a `values.yaml` file containing:
```yaml
container:
  image: some-other-image:v1.0.0
  port: 81
```

I should be able to provide these values during `pctl install` and see the resulting artifact updated:
```
$ pctl install my-catalog/weaveworks-nginx/v0.1.0 --values values.yaml
Generating artifacts....

$ cat weaveworks-nginx/raw-yamls/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: some-other-image:v1.0.0
        ports:
        - containerPort: 81
