### ISSUE TITLE
As a Profile Author I want to be able to provide a pre-configured set of helm values for a helm artifact

### ISSUE THREAD

**Issue by aclevername** [weaveworks/pctl#58]
As a Profile Author I want to be able to provide a pre-configured set of helm values for a helm artifact. 

Lets say I'm a big fan of the [bitnami-nginx chart](https://github.com/bitnami/charts/tree/master/bitnami/nginx) and I am creating a profile that has it as an artifact. This chart has hundreds of configuration options, but as the profile author I have some opinions about some of these values and want to configure them myself, removing the need for the user to do so themselves. Lets say by default my company wants all components to omit promethues metrics. This is currently a configuration option in the helm chart values file:
```yaml
## Prometheus Exporter / Metrics
##
metrics:  
  enabled: false
```

Rather than having everyone that consumes this profile configure this, I want to be able to specify in my profile definition that `metrics.enabled` should be `true`

## Example
Given a profile:

``` bash
$ tree weaveworks-nginx/
├── profile.yaml
```

`profile.yaml` contains:
```yaml
apiVersion: profiles.fluxcd.io/v1alpha1
kind: Profile
metadata:
  name: weaveworks-nginx
spec:
  description: Profile for deploying nginx
  version: v0.1.0
  artifacts:
    - name: nginx
      kind: HelmChart
      chart:
        url: https://charts.bitnami.com/bitnami
        name: nginx
        version: "11.1.6"
```

I should be able to define some pre-existing helm values that should be applied correctly during `pctl install`. 

## Option 1 - inline values
I can provide a `values` section in my artifact, that get consumed during `pctl install`. For example the new `profile.yaml` contains:

```yaml
apiVersion: profiles.fluxcd.io/v1alpha1
kind: Profile
metadata:
  name: weaveworks-nginx
spec:
  description: Profile for deploying nginx
  version: v0.1.0
  artifacts:
    - name: nginx
      kind: HelmChart
      chart:
        url: https://charts.bitnami.com/bitnami
        name: nginx
        version: "11.1.6"
      values:
         metrics:
             enabled: true
```

## Option 2 - values file artifact
I can provide a `values.yaml` artifact that gets consumed during `pctl install`. For example the new `profile.yaml` contains:

```yaml
apiVersion: profiles.fluxcd.io/v1alpha1
kind: Profile
metadata:
  name: weaveworks-nginx
spec:
  description: Profile for deploying nginx
  version: v0.1.0
  artifacts:
    - name: nginx
      kind: HelmChart
      chart:
        url: https://charts.bitnami.com/bitnami
        name: nginx
        version: "11.1.6"
      valuesFile: nginx/values.yaml # we can do better than this, just an example
```

```
$ cat nginx/values.yaml
metrics:
   enabled: true
```

---

For either approach, the end result should be the values being provided via configmap/or inlined in the helm-release:
```yaml
$ pctl install my-catalog/weaveworks-nginx/v0.1.0
Generating artifacts...

$ cat weaveworks-nginx/nginx/HelmRepositoy.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  creationTimestamp: null
  name: pctl-profile-weaveworks-nginx-dokuwiki
  namespace: default
spec:
  chart:
    spec:
      chart: dokuwiki
      sourceRef:
        kind: HelmRepository
        name: pctl-profile-profiles-examples-dokuwiki
        namespace: default
      version: 11.1.6
      ## Inline using Values
      values:
        metrics:
          enabled: true
      ## Alternatively use configmap
      valuesFrom:
      - kind: ConfigMap
        name: weaveworks-nginx-values
  interval: 0s
  ```
  
  
# Open issues
How does this integrate with the existing ability for users to provide helm values?
```
pctl install my-catalog/weaveworks-nginx/v0.1.0 --config-map my-helm-values-config-map
```

This currently results in:
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  creationTimestamp: null
  name: pctl-profile-weaveworks-nginx-dokuwiki
  namespace: default
spec:
  chart:
    spec:
      chart: dokuwiki
      sourceRef:
        kind: HelmRepository
        name: pctl-profile-profiles-examples-dokuwiki
        namespace: default
      version: 11.1.6
      valuesFrom:
      - kind: ConfigMap
        name: my-helm-values-config-map
  interval: 0s
  ```

Should we try to do some clever merge? How does the Helm controller deal with multiple sources specifying the same values?

**Comment by Callisto13** [comment]
Doing this with a `valuesFile` (or eq) is a little fiddly, since we would need to:
- Download the profile definition (we already do this)
- Loop over the artifacts to see which Helm ones specify a `valuesFile`
- Download that values file
- Read it and use the values etc

This feels like a lot of traffic for if a profile had, say, 5+ Helm charts and all define their own values file.

A single profile-wide values file would be easier on the network, but more complex for if/when we want to configure different Artifact kinds.

We can start off with just inlining the values in the Artifact definition, but some way of doing this through files would need to be done at some point as I can see users asking for it.

**Comment by Callisto13** [comment]
And yeh merging will be fun, nested maps and all. Eg the def has:

```json
{
"foo": "bar",
"level1": {
    "baz": 8081,
    "level2": {
        "animal": "dog"
    }
  }
}
```

and the sub has:

```json
{
"level1": {
    "level2": {
        "animal": "cat"
    }
  }
}
```

fun times

**Comment by aclevername** [comment]
> We can start off with just inlining the values in the Artifact definition, but some way of doing this through files would need to be done at some point as I can see users asking for it.

Sounds like a great start to me :ok_hand:

**Comment by Callisto13** [comment]
Okay so verified that if I leave HelmRelease to its own devices, the author's default settings will override the installer's configmap settings.

We may need to be clever about it, and do something like read the user's configmap, merge with the author's settings and create a new configmap which will be applied, but really that just feels... wrong.

**Comment by Callisto13** [comment]
Bleh doing that (on our side) would involve shelling out to kubectl from pctl which i do not like.

So thinking out loud how about this:

When given a HelmRelease spec containing the following:
```yaml
valuesFrom:
- kind: ConfigMap
  name: nginx-values
  valuesKey: one.yaml
- kind: ConfigMap
  name: nginx-values
  valuesKey: two.yaml
```
The values in each entry are overridden by the last. 2 configmaps with the following:
```yaml
data:
  values.yaml: |
    replicaCount: 5
    service:
      port: 8082
  valuess.yaml: |
    replicaCount: 1
```
with the order set in the above HelmRelease will result in a deployment with `replicas: 1` and `service.port: 8082`.

So how could we use this?

- The profile author supplies some default values (either HR inline, or a file of our structure, or inline values of our structure, whatever) (i still don't want to be downloading a file per artifact but that is another thing)
- We process them into a configmap, that becomes one of the generated artifacts `default-values-artifactname.yaml` or smth
- The HelmRelease has that configmap set as the `valuesFrom` field
- The user's configmap, if not nil, is appended to the array in the last place.
