### ISSUE TITLE
pctl install should organise artifact resources in sub-folders

### ISSUE THREAD

**Issue by aclevername** [weaveworks/pctl#59]
currently pctl install outputs:
```
$ pctl install nginx-catalog/weaveworks-nginx/v0.1.0
generating subscription for profile nginx-catalog/weaveworks-nginx:

$ tree weaveworks-nginx
weaveworks-nginx
├── GitRepository-0.yaml
├── GitRepository-1.yaml
├── HelmRelease-2.yaml
├── HelmRelease-4.yaml
├── HelmRepository-5.yaml
├── Kustomization-3.yaml
└── profile.yaml
```

for profile
```
apiVersion: profiles.fluxcd.io/v1alpha1
kind: Profile
metadata:
  name: weaveworks-nginx
spec:
  description: Profile for deploying nginx
  version: v0.1.0
  artifacts:
    - name: nested-profile
      kind: Profile
      profile:
        url: https://github.com/weaveworks/profiles-examples
        version: bitnami-nginx/v0.0.1
    - name: nginx-deployment
      path: nginx/deployment
      kind: Kustomize
    - name: dokuwiki
      kind: HelmChart
      chart:
        url: https://charts.bitnami.com/bitnami
        name: dokuwiki
        version: "11.1.6"
 ```
 
 Lets change it so it outputs like:
 ```
 tree weaveworks-nginx
weaveworks-nginx
├── nested-profile
       ├── GitRepository.yaml
       ├── HelmRelease.yaml
├── dokuwiki
       ├── HelmRelease.yaml
       ├── HelmRepository.yaml
├── nginx-deployment
       ├── GitRepository.yaml
       ├── Kustomization.yaml
└── profile.yaml
```
